services:
  - type: web
    name: invoiceocr-api
    env: python
    plan: free  # or starter/pro
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn invoiceocr.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: invoiceocr.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - fromDatabase:
          name: my-db
          property: connectionString

databases:
  - name: my-db
    plan: free
